name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      - name: Wait for MySQL
        run: |
          until docker exec mysql \
            mysqladmin ping -h "localhost" -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run tests
        run: docker compose exec -T store_manager_app pytest
